basePath: /api
definitions:
  entity.UploadedFileRps:
    properties:
      fileId:
        type: string
      path:
        type: string
      size:
        type: integer
    type: object
  entity.UserLoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  entity.UserLoginRps:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: XXXXX Backend Server
  title: XXXXX 接口文档
  version: "1.0"
paths:
  /file/uploadFile:
    post:
      description: 本地文件上传
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/entity.UploadedFileRps'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: 本地文件上传
      tags:
      - 文件管理
  /user/login:
    post:
      description: 用户登录
      parameters:
      - description: 请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.UserLoginReq'
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/entity.UserLoginRps'
        "500":
          description: Internal Server Error
      summary: 用户登录
      tags:
      - 用户账户管理
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
